/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.requirements.BIE;

import com.requirements.models.BIEData;
import com.requirements.models.BIEMainViewTableModel;
import javax.swing.JFrame;

/**
 *
 * @author keduardo
 */
public class BIEMonthlyView extends javax.swing.JFrame {

    private BIEMainViewTableModel tableModel;
    /**
     * Creates new form BIEMonthlyView
     */
    public BIEMonthlyView() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btnAfterActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        btnBefore = new javax.swing.JButton();
        btnAfter = new javax.swing.JButton();
        lblMonth = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecords);

        btnBefore.setText("Anterior");
        btnBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeforeActionPerformed(evt);
            }
        });

        btnAfter.setText("Siguiente");
        btnAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfterActionPerformed(evt);
            }
        });

        lblMonth.setText("Mayo");

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblBalance.setText("Balance:$50000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBefore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAfter)
                        .addGap(44, 44, 44)
                        .addComponent(lblMonth)
                        .addGap(89, 89, 89)
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBefore)
                    .addComponent(btnAfter)
                    .addComponent(lblMonth)
                    .addComponent(lblBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeforeActionPerformed
        // TODO add your handling code here:
        this.tableModel = new BIEMainViewTableModel();
        this.lblBalance.setText("Balance: $50000");
        this.tableModel.addToList("Deposito del Cliente Gilberto", "Abril 8 18:00", "$15000");
        this.tableModel.addToList("Deposito del Cliente Ramirez", "Abril 10 12:00", "$45000");
        this.tableModel.addToList("Deposito del Cliente Canto", "Abril 15 18:00", "$15000");
        this.tableModel.addToList("Pago a Provedor", "Abril 19 13:00", "-$12000");
        this.tableModel.addToList("Pago de nominas", "Abril 30 13:00", "-$36000");
        this.tblRecords.setModel(tableModel);
        this.tblRecords.updateUI();
        this.lblMonth.setText("Abril");
    }//GEN-LAST:event_btnBeforeActionPerformed

    private void btnAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfterActionPerformed
        // TODO add your handling code here:
        this.tableModel = new BIEMainViewTableModel();
        this.lblBalance.setText("Balance: $50000");
        this.tableModel.addToList("Deposito del Cliente Canto", "Mayo 18 18:00", "$15000");
        this.tableModel.addToList("Pago a Pintores", "Mayo 19 13:00", "-$2000");
        this.tableModel.addToList("Pago a provedores", "Mayo 20 13:00", "-$4000");
        this.tblRecords.setModel(tableModel);
        this.tblRecords.updateUI();
        this.lblMonth.setText("Mayo");
    }//GEN-LAST:event_btnAfterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfter;
    private javax.swing.JButton btnBefore;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables
}
